<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.newtours.testcase.LoginPageTest" tests="6" time="81.978" ignored="0" failures="1" timestamp="15 May 2018 17:17:52 GMT" skipped="3" hostname="DESKTOP-6GG2TDV" errors="0">
  <testcase name="validateloginPageTitle" time="11.480" classname="com.newtours.testcase.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [Hello vivek Welcome: Mercury Tours] but found [Welcome: Mercury Tours]">
      <![CDATA[java.lang.AssertionError: expected [Hello vivek Welcome: Mercury Tours] but found [Welcome: Mercury Tours]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.newtours.testcase.LoginPageTest.validateloginPageTitle(LoginPageTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateloginPageTitle -->
  <testcase name="ClickOnRegistrationButton" time="12.554" classname="com.newtours.testcase.LoginPageTest"/>
  <testcase name="CheckFindAFlightTextIsAvailable" time="13.021" classname="com.newtours.testcase.LoginPageTest"/>
  <testcase name="validateloginPageTitle" time="16.913" classname="com.newtours.testcase.LoginPageTest">
    <skipped/>
  </testcase> <!-- validateloginPageTitle -->
  <testcase name="validateloginPageTitle" time="14.724" classname="com.newtours.testcase.LoginPageTest">
    <skipped/>
  </testcase> <!-- validateloginPageTitle -->
  <testcase name="validateloginPageTitle" time="13.286" classname="com.newtours.testcase.LoginPageTest">
    <skipped/>
  </testcase> <!-- validateloginPageTitle -->
</testsuite> <!-- com.newtours.testcase.LoginPageTest -->
